auto-mat/do-prace-na-kole

dpnk/templates/base_generic.html, dpnk/templates/registration/diplomas.html, dpnk/test/test_views.py, dpnk/views.py
=> Don't show listings for team results when there was no team

dpnk/templates/registration/team_admin_members.html, project/settings.py
=> Configure Photologue image storage dir

dpnk/locale/cs/LC_MESSAGES/django.po, dpnk/locale/dsnkcs/LC_MESSAGES/django.po, dpnk/locale/en/LC_MESSAGES/django.po, dpnk/templates/base_generic.html
=> Změnít is spelled změnit

apps/t_shirt_delivery/actions.py
Pár drobností, aby byl proces generování PDF jednodušší.
=> make generating delivery PDFs more convenient

apps/dpnk/models/subsidiary.py, apps/t_shirt_delivery/admin.py, apps/t_shirt_delivery/models/delivery_batch.py
- Údaje o adresátovi je potřeba zadat všechny dohromady
- Výpis počtu týmových balíčků
=> Opravy pro generování dávek

apps/dpnk/rest.py, project/urls.py
Add REST endpoint for get photo URL. Require for access avatar image via Metabase app.
=> apps/dpnk: add REST endpoint for get photo URL

project/settings/base.py
Enable request from 'https://metabase.dopracenakole.net' URL.
=> project/settings: enable request from 'https://metabase.dopracenakole.net' URL

apps/dpnk/templates/dpnk/datareport.html
=> apps/dpnk: open Metabase data report dashboard in new tab via link

apps/dpnk/locale/en/LC_MESSAGES/django.po
Updates the message files for the given en locale. Translate string from cs locale "Otevřít na nové kartě" to en locale "Open in new tab".
=> apps/dpnk: updates the message files for the given en locale

apps/t_shirt_delivery/admin.py
Add "DeliveryBatch" admin model "wellpack_csv_data_url" list display field.
=> apps/t_shirt_delivery: add "DeliveryBatch" admin model "wellpack_csv_data_url" list display field

apps/t_shirt_delivery/admin.py, apps/t_shirt_delivery/delivery_batch_resources.py, apps/t_shirt_delivery/models/delivery_batch.py, apps/t_shirt_delivery/test/test_admin.py
Export `DeliveryBatch` model with product codes as column names.
=> apps/t_shirt_delivery: export DeliveryBatch model with product codes as column names

apps/dpnk/locale/en/LC_MESSAGES/django.po, apps/dpnk/templates/company_admin/invoices.html, apps/dpnk/test/test_company_admin_views.py
Fix show old way maked invoices on faktury/ URL web page, created before Fakturoid global env var date `FAKTUROID_DATE_FROM_CREATE_INVOICES`.
=> apps/dpnk: fix show old way maked invoices on faktury/ URL web page

apps/t_shirt_delivery/forms.py, apps/t_shirt_delivery/locale/en/LC_MESSAGES/django.po, apps/t_shirt_delivery/templates/registration/change_tshirt.html, apps/t_shirt_delivery/views.py
Adjust zmenit_triko/ URL HTML template texts.
=> apps/t_shirt_delivery: adjust zmenit_triko/ URL HTML template texts

apps/t_shirt_delivery/locale/en/LC_MESSAGES/django.po
Fix zmenit_triko/ URL HTML template en translation texts.
=> apps/t_shirt_delivery: fix zmenit_triko/ URL HTML template en translation texts

apps/dpnk/fakturoid_invoice_gen.py, apps/t_shirt_delivery/delivery_batch_resources.py
Fix Fakturoid invoice number, and `fix get_all_t_shirt_codes` return value during run tests.
=> apps/dpnk: fix Fakturoid invoice number

apps/dpnk/fakturoid_invoice_gen.py
Fix Fakturoid invoice number format #yyyy#D#dddd#.
=> apps/dpnk: fix Fakturoid invoice number format

apps/dpnk/fakturoid_invoice_gen.py
Send Fakturoid invoice by email also for production account.
=> apps/dpnk: send Fakturoid invoice by email also for production account

apps/dpnk/fakturoid_invoice_gen.py, apps/dpnk/fakturoid_invoice_send_by_email.py
Fix send Fakturoid invoice with production account.
=> apps/dpnk: fix send Fakturoid invoice with production account

apps/dpnk/tasks.py
Disable send email notification for unpaid Fakturoid invoices. The notification will be processed by Fakturoid.
=> apps/dpnk: disable send email notification for unpaid Fakturoid invoices

apps/dpnk/fakturoid_invoice_gen.py
Fix Fakturoid subject phone number. Use only one administrator phone number without a space.
=> apps/dpnk: fix Fakturoid subject phone number

apps/dpnk/models/invoice.py
Try disable DB denormalization for Invoice `add_payments()` method.
=> apps/dpnk: try disable DB denormalization for Invoice add_payments() method

apps/dpnk/tasks.py
Log `create_invoice_if_needed()` task function.
=> apps/dpnk: log create_invoice_if_needed() task function

apps/dpnk/templates/dpnk/datareport.html
Filter Metabase individual dashboard by unique username field.
=> apps/dpnk: filter Metabase individual dashboard by unique username field

apps/dpnk/fakturoid_invoice_gen.py
Fix Fakturoid Subject street format.
=> apps/dpnk: fix Fakturoid Subject street format

apps/dpnk/management/commands/get_city_trip_geodata.py, apps/dpnk/management/commands/mount_aws_s3_bucket.sh, docker-compose.yml, monorepo/docker-base-image/Dockerfile, monorepo/docker-base-image/poetry.lock, monorepo/docker-base-image/pyproject.toml
Get city user defined buffer clipped trip geodata as GPKG format, which is uploaded into AWS S3 Bucket.
`python manage.py get_city_trip_geodata --city "Brandýs nad Labem" --buffer 100`
=> apps/dpnk/management/commands: add get_city_trip_geodata command

apps/dpnk/forms.py, apps/dpnk/templates/dpnk/payment_type.html
Fix payment type form/template texts.
=> apps/dpnk: fix payment type form/template texts

monorepo/docker-base-image/poetry.lock
Reverts auto-mat/do-prace-na-kole#223
=> Revert "Bump ipython from 7.24.1 to 7.31.1 in /monorepo/docker-base-image"

apps/dpnk/models/questionnaire.py, monorepo/docker-base-image/poetry.lock, monorepo/docker-base-image/pyproject.toml
=> apps/dpnk: run enable_voting_on() method if Answer model is loaded

project/settings/base.py
=> project/settings: Fix Django REST framework default schema class setting

apps/dpnk/rest.py
=> apps/dpnk: Fix get REST API rest-docs/ URL

monorepo/docker-base-image/poetry.lock, monorepo/docker-base-image/pyproject.toml
Quick fix:
Show radio buttons widget for "Přejete si od nás dostávat zprávy?" question on the vytvorit_profil/ URL page.
Fixes #275 .
=> monorepo/docker-base-image: Downgrade django-crispy-forms==1.11.2

apps/t_shirt_delivery/admin.py, apps/t_shirt_delivery/models/delivery_batch.py
Allow export `DeliveryBatch` models via actions and with Celery.
=> apps/t_shirt_delivery: allow export DeliveryBatch models via actions

apps/dpnk/auth.py, apps/dpnk/forms.py, apps/dpnk/locale/en/LC_MESSAGES/django.po
Allow register email address with lowercase letter only and enable a case-insensitive login email address.
=> Allow register email address with lowercase letter only and enable a case-insensitive login email address

apps/dpnk/templates/dpnk/view_trip.html
Hide record time period input field, URL https://dpnk.dopracenakole.cz/jizdy.
=> apps/dpnk/templates/dpnk: hide record time period input field

apps/dpnk/templates/email/base.html
=> apps/dpnk/templates/email: fix email DPNK logo img URL path and height size

apps/dpnk/auth.py
=> Disable registration button after the date of the registration phase is exceeded

apps/dpnk/rest.py
Make REST API this_campaign/ URL endpoint public.
=> apps/dpnk: make REST API this_campaign/ URL endpoint public

apps/dpnk/rest.py
Fix filtering mechandize REST API URL endpoint by 'nic' code.
=> apps/dpnk: fix filtering mechandize REST API URL endpoint by 'nic' code

project/settings/rtwbb.py
Add RTWBB project settings file, for dev/testing purpose.
=> project/settings: add rtwbb project settings file

apps/dpnk/rest.py
Add discount coupon REST API URL endpoint.
URL:
- discount-coupon/\<CODE\>/
=> apps/dpnk: add discount coupon REST API URL endpoint

apps/dpnk/rest.py, apps/dpnk/test/test_rest.py
Add this campaign REST API URL endpoint max_team_members field.
=> apps/dpnk: add this campaign REST API URL endpoint max_team_members field

apps/dpnk/rest.py
Fix PayU create new order REST API URL endpoint getting/creating user attendance model instance.
=> apps/dpnk: fix PayU create new order REST API URL endpoint getting/creating user attendance model instance

apps/dpnk/rest.py, apps/dpnk/urls.py
Add is user organization admin REST API URL endpoint.
URL:
- is-user-organization-admin/
=> apps/dpnk: add is user organization admin REST API URL endpoint

apps/dpnk/rest.py, apps/dpnk/urls.py
Add has organization admin REST API URL endpoint.
URL:
- has-organization-admin/<ORGANIZATION_ID>/
=> apps/dpnk: add has organization admin REST API URL endpoint

apps/dpnk/rest.py
Add register challenge REST API URL endpoint `organization_type` readonly field.
=> apps/dpnk: add register challenge REST API URL endpoint organization_type readonly field.

apps/dpnk/rest.py, apps/dpnk/rest_permissions.py
Make register challenge REST API URL endpoint subsidiary_id, organization_id field readonly.
=> apps/dpnk: make register challenge REST API URL endpoint subsidiary_id, organization_id field readonly

apps/dpnk/rest.py
Add this campaign REST API URL endpoint price_level field.
=> apps/dpnk: add this campaign REST API URL endpoint price_level field
